#!/usr/bin/env python3
"""SlideMaster v2 - bounded Codex app-server stdio transport.

Usage: create CodexProvider, call preflight(), then start_turn(...).
Example: with CodexProvider() as provider: provider.preflight()
Dependencies: Python standard library and an already installed Codex CLI.

Wire values follow the schema generated by Codex 0.153.4. In particular,
thread/start uses ``workspace-write`` whereas turn/start uses ``workspaceWrite``.
See https://learn.chatgpt.com/docs/app-server for the connection lifecycle.
No credentials, global configuration, or approval policy rules are written here.
"""

from __future__ import annotations

import json
import os
import platform
import re
import queue
import shutil
import subprocess
import threading
import time
from collections.abc import Callable
from pathlib import Path
from typing import Any

from .stdio_transport import StdioTransport, TransportError, resolve_command

EventCallback = Callable[[dict[str, Any]], None]
_USER_REQUESTS = {
    "item/commandExecution/requestApproval",
    "item/fileChange/requestApproval",
    "item/tool/requestUserInput",
    "item/permissions/requestApproval",
    "mcpServer/elicitation/request",
}


class ProviderError(RuntimeError):
    """A transport failure that must not be mistaken for successful generation."""

    def __init__(self, code: str, message: str) -> None:
        super().__init__(message)
        self.code = code


class CodexProvider:
    """Own one local app-server process and deliver notifications asynchronously.

    Callbacks run serially on a separate dispatcher, so they may call respond()
    or cancel() without blocking the protocol reader. A callback must return
    promptly; the bounded event queue fails closed if its consumer falls behind.
    Server-side request ids retain their JSON type, including integer ids.
    """

    def __init__(
        self,
        *,
        command: list[str] | None = None,
        request_timeout: float = 30.0,
        turn_timeout: float = 1800.0,
        max_frame_bytes: int = 4 * 1024 * 1024,
        max_stream_bytes: int = 128 * 1024 * 1024,
        max_stderr_bytes: int = 64 * 1024,
        event_queue_size: int = 256,
    ) -> None:
        if min(request_timeout, turn_timeout, max_frame_bytes, max_stream_bytes,
               max_stderr_bytes, event_queue_size) <= 0:
            raise ValueError("Provider timeouts and output bounds must be positive")
        self.command = command or ["codex", "app-server", "--listen", "stdio://"]
        self.request_timeout = request_timeout
        self.turn_timeout = turn_timeout
        self.max_frame_bytes = max_frame_bytes
        self.max_stream_bytes = max_stream_bytes
        self.max_stderr_bytes = max_stderr_bytes
        self._lock = threading.RLock()
        self._write_lock = threading.Lock()
        self._start_lock = threading.Lock()
        self._lifecycle_lock = threading.Lock()
        self._termination_lock = threading.Lock()
        self._stop = threading.Event()
        self._process: subprocess.Popen[bytes] | None = None
        self._transport: StdioTransport | None = None
        self._threads: list[threading.Thread] = []
        self._pending: dict[int, dict[str, Any]] = {}
        self._requests: dict[int | str, dict[str, Any]] = {}
        self._callbacks: dict[str, EventCallback] = {}
        self._starting_callback: EventCallback | None = None
        self._active: dict[tuple[str, str], float] = {}
        self._events: queue.Queue[tuple[EventCallback, dict[str, Any]]] = queue.Queue(event_queue_size)
        self._next_id = 0
        self._failure: ProviderError | None = None
        self._failure_callbacks: list[tuple[str | None, EventCallback]] = []
        self._initialized = False
        self._closed = False
        self._terminated = False
        self._stderr_tail = bytearray()
        self._stream_bytes = 0
        self._models: list[dict[str, Any]] = []
        self._ready = False
        self._server: dict[str, Any] = {}
        self._resolved_launcher: str | None = None
        self._runtime: dict[str, Any] = {"status": "UNVERIFIED", "reason": "Runtime discovery has not run"}

    def __enter__(self) -> CodexProvider:
        return self

    def __exit__(self, *args: object) -> None:
        self.close()

    def _ensure_started(self) -> None:
        with self._lifecycle_lock:
            if self._closed:
                raise ProviderError("CLOSED", "Codex connection is closed; create a new provider")
            if self._failure:
                raise self._failure
            if self._initialized:
                return
            launch_environment = self._runtime_environment()
            launch_command = self.command[:]
            if self._resolved_launcher:
                # PATH now includes the native payload. Keep the original npm
                # JS launcher so its package-manager metadata still applies.
                launch_command[0] = self._resolved_launcher
            self._launch_process(launch_command, env=launch_environment)
            for target in (self._read_stdout, self._read_stderr, self._dispatch, self._watchdog):
                worker = threading.Thread(target=target, daemon=True, name=f"codex-{target.__name__}")
                self._threads.append(worker)
                worker.start()
            initialized = self._rpc("initialize", {
                "clientInfo": {"name": "slidemaster_v2", "title": "SlideMaster", "version": "2.0.0"},
                "capabilities": {"experimentalApi": True},
            })
            self._server = {key: initialized[key] for key in ("userAgent", "platformFamily", "platformOs") if key in initialized}
            self._send({"method": "initialized", "params": {}})
            self._initialized = True

    def _launch_process(self, command: list[str], *, cwd=None, env=None) -> None:
        """Shared bounded stdio lifecycle; provider subclasses retain their wire."""
        try:
            self._transport = StdioTransport.launch(command, cwd=cwd, env=env,
                max_frame_bytes=self.max_frame_bytes, startup_timeout=self.request_timeout)
            self._process = self._transport.process
        except TransportError as exc:
            raise ProviderError(exc.code, str(exc)) from exc
        except OSError as exc:
            raise ProviderError("UNAVAILABLE", "Local CLI could not start; check the installed executable") from exc

    def _runtime_environment(self) -> dict[str, str] | None:
        """Resolve bundled helpers without global installs or PATH mutation.

        Desktop installations commonly expose only a symlink to ``codex`` in
        ~/.local/bin. The 0.153.4 app-server starts codex-code-mode-host by name;
        its sibling in the application bundle must therefore be on the *child*
        PATH. Resolving the actual executable also keeps helper and CLI versions
        paired. Custom protocol peers do not require Codex's helper binaries.
        """
        if not self.command or Path(self.command[0]).name.lower() not in {"codex", "codex.exe", "codex.cmd", "codex.bat"}:
            self._runtime = {"status": "UNVERIFIED", "reason": "Custom transport command; file capability must be checked by its owner"}
            return None
        executable = shutil.which(self.command[0])
        if not executable:
            self._runtime = {"status": "BLOCKED", "reason": "Codex executable is not available on PATH"}
            return None
        binary = Path(executable).resolve()
        if binary.suffix.lower() in {'.cmd', '.bat'}:
            try:
                resolved = resolve_command([executable])
            except TransportError as exc:
                raise ProviderError(exc.code, str(exc)) from exc
            binary = Path(resolved[1])  # Official JS, never execute the batch shim.
        suffix = '.exe' if platform.system() == 'Windows' else ''
        bundled_host = binary.parent / ("codex-code-mode-host" + suffix)
        host_discovery = "bundled_sibling"
        npm_bundle = self._npm_bundle(binary)
        if npm_bundle:
            bundle_directory, host_discovery = npm_bundle
            self._resolved_launcher = str(Path(executable).absolute())
            bundled_host = bundle_directory / ("codex-code-mode-host" + suffix)
        host_on_path = shutil.which("codex-code-mode-host" + suffix)
        if bundled_host.is_file() and os.access(bundled_host, os.X_OK):
            # The child already inherits this environment by default. Only PATH
            # is changed; credentials and unrelated values are never inspected
            # or returned as diagnostic metadata.
            child_environment = os.environ.copy()
            child_environment["PATH"] = str(bundled_host.parent) + os.pathsep + child_environment.get("PATH", "")
            self._runtime = {"status": "PARTIALLY_VERIFIED", "code_mode_host": str(bundled_host),
                             "host_discovery": host_discovery, "child_path_adjusted": True,
                             "reason": "Bundled helper is executable; actual stage file execution is validated separately"}
            return child_environment
        if host_on_path:
            self._runtime = {"status": "PARTIALLY_VERIFIED", "code_mode_host": str(Path(host_on_path).resolve()),
                             "host_discovery": "existing_path", "child_path_adjusted": False,
                             "reason": "Existing helper is executable; actual stage file execution is validated separately"}
            return None
        self._runtime = {"status": "BLOCKED", "code_mode_host": None, "child_path_adjusted": False,
                         "reason": "codex-code-mode-host is missing; restore the helper bundled with the installed Codex application before file tasks"}
        return None

    @staticmethod
    def _npm_bundle(launcher: Path) -> tuple[Path, str] | None:
        """Resolve the official npm launcher's paired native payload, without JS.

        Official 0.153.4 source:
        https://github.com/openai/codex/blob/rust-v0.153.4/codex-cli/bin/codex.js
        npm optional platform packages are aliases: their manifests still name
        @openai/codex, with a version such as 0.153.4-darwin-arm64. Read only
        bounded package metadata; never scan binaries, credentials, or config.
        """
        if launcher.name != "codex.js" or launcher.parent.name != "bin":
            return None
        targets = {
            ("Darwin", "arm64"): ("darwin", "arm64", "aarch64-apple-darwin"),
            ("Darwin", "aarch64"): ("darwin", "arm64", "aarch64-apple-darwin"),
            ("Darwin", "x86_64"): ("darwin", "x64", "x86_64-apple-darwin"),
            ("Linux", "aarch64"): ("linux", "arm64", "aarch64-unknown-linux-musl"),
            ("Linux", "arm64"): ("linux", "arm64", "aarch64-unknown-linux-musl"),
            ("Linux", "x86_64"): ("linux", "x64", "x86_64-unknown-linux-musl"),
            ("Windows", "amd64"): ("win32", "x64", "x86_64-pc-windows-msvc"),
            ("Windows", "x86_64"): ("win32", "x64", "x86_64-pc-windows-msvc"),
            ("Windows", "arm64"): ("win32", "arm64", "aarch64-pc-windows-msvc"),
            ("Windows", "aarch64"): ("win32", "arm64", "aarch64-pc-windows-msvc"),
        }
        target = targets.get((platform.system(), platform.machine().lower()))
        if not target:
            return None

        def manifest(path: Path) -> dict[str, Any] | None:
            try:
                if path.is_symlink():
                    return None
                with path.open("rb") as stream:
                    raw = stream.read(65537)
                if len(raw) > 65536:
                    return None
                value = json.loads(raw)
                return value if isinstance(value, dict) else None
            except (OSError, ValueError, UnicodeError, RecursionError):
                return None

        package_root = launcher.parent.parent
        package = manifest(package_root / "package.json")
        if not package or package.get("name") != "@openai/codex" or package.get("bin") != {"codex": "bin/codex.js"}:
            return None
        version = package.get("version")
        if not isinstance(version, str) or not re.fullmatch(r"[0-9]+\.[0-9]+\.[0-9]+(?:-[A-Za-z0-9.-]+)?", version):
            return None
        target_os, arch, triple = target
        suffix = f"{target_os}-{arch}"
        platform_name = f"@openai/codex-{suffix}"
        optional = package.get("optionalDependencies")
        if not isinstance(optional, dict) or optional.get(platform_name) != f"npm:@openai/codex@{version}-{suffix}":
            return None
        # Match Node's ancestor node_modules lookup, including nested npm/pnpm
        # optional dependencies. Do not search arbitrary home/global directories.
        bundle_root = None
        for directory in (launcher.parent, *launcher.parent.parents[:24]):
            if directory.name == "node_modules":
                continue
            package_json = directory / "node_modules" / platform_name / "package.json"
            if not package_json.exists():
                continue
            native = manifest(package_json)
            if (not native or native.get("name") != "@openai/codex"
                    or native.get("version") != f"{version}-{suffix}"
                    or native.get("os") != [target_os] or native.get("cpu") != [arch]):
                return None  # Never pair the main launcher with another version.
            bundle_root = package_json.parent
            break
        discovery = "npm_platform_package" if bundle_root else "npm_embedded_vendor"
        binary_directory = (bundle_root or package_root) / "vendor" / triple / "bin"
        executable_suffix = '.exe' if target_os == 'win32' else ''
        if not all((binary_directory / (name + executable_suffix)).is_file()
                   and os.access(binary_directory / (name + executable_suffix), os.X_OK)
                   for name in ("codex", "codex-code-mode-host")):
            return None
        return binary_directory.resolve(), discovery

    def preflight(self) -> dict[str, Any]:
        """Check the existing login and model catalog; return no account identifiers."""
        self._ensure_started()
        account_result = self._rpc("account/read", {"refreshToken": False})
        account = account_result.get("account")
        authenticated = isinstance(account, dict)
        self._models = []
        cursor = None
        seen: set[str] = set()
        for _ in range(20):
            params: dict[str, Any] = {"limit": 100, "includeHidden": False}
            if cursor:
                params["cursor"] = cursor
            result = self._rpc("model/list", params)
            if not isinstance(result.get("data"), list):
                raise ProviderError("INVALID_RESPONSE", "Codex model/list returned an invalid catalog")
            for model in result["data"]:
                if not isinstance(model, dict) or not isinstance(model.get("model"), str):
                    raise ProviderError("INVALID_RESPONSE", "Codex returned an invalid model entry")
                self._models.append({key: model[key] for key in (
                    "id", "model", "displayName", "isDefault", "defaultReasoningEffort", "supportedReasoningEfforts",
                ) if key in model})
            cursor = result.get("nextCursor")
            if not cursor:
                break
            if not isinstance(cursor, str) or cursor in seen:
                raise ProviderError("INVALID_RESPONSE", "Codex model pagination did not advance")
            seen.add(cursor)
        else:
            raise ProviderError("OUTPUT_LIMIT", "Codex model catalog exceeds the pagination limit")
        requires_auth = bool(account_result.get("requiresOpenaiAuth", True))
        auth_type = account.get("type") if authenticated else None
        auth_mode = ("subscription" if auth_type == "chatgpt"
                     else "api_key" if auth_type == "apiKey"
                     else "unknown" if authenticated or not requires_auth else "none")
        ready = bool(self._models) and auth_mode == "subscription" and self._runtime["status"] != "BLOCKED"
        self._ready = ready
        limits: dict[str, Any] | None = None
        limits_status = "UNAVAILABLE"
        if ready:
            try:
                rate_result = self._rpc("account/rateLimits/read", {})
                buckets = rate_result.get("rateLimitsByLimitId") or {"codex": rate_result.get("rateLimits", {})}
                if isinstance(buckets, dict):
                    limits = {}
                    for key, bucket in buckets.items():
                        if not isinstance(bucket, dict):
                            continue
                        limits[key] = {}
                        for window_name in ("primary", "secondary"):
                            window = bucket.get(window_name)
                            if isinstance(window, dict):
                                limits[key][window_name] = {
                                    field: window[field] for field in ("usedPercent", "windowDurationMins", "resetsAt") if field in window
                                }
                    limits_status = "VERIFIED"
            except ProviderError as exc:
                if self._failure:
                    raise
                # Some authenticated providers do not expose account limits.
                # Preserve unavailable as null, never interpret it as zero use.
                limits_status = exc.code
        return {
            "provider": "codex",
            "ready": ready,
            "auth_mode": auth_mode,
            "features": {"streaming": True, "approvals": True, "user_input": True,
                         "image_view": True, "resume": True, "cancel": True,
                         "workspace_isolation": "workspace-write", "subscription_only": True},
            "authenticated": authenticated,
            "auth_type": account.get("type") if authenticated else None,
            "requires_auth": requires_auth,
            "models": self._models,
            "server": self._server,
            "runtime": self._runtime,
            "default_model": next((m["model"] for m in self._models if m.get("isDefault")), None),
            "effective_model_source": "thread/start response; global configuration is not read",
            "reason": None if ready else (self._runtime["reason"] if self._runtime["status"] == "BLOCKED" else "Sign in with a native ChatGPT subscription in Codex; API billing and unknown authentication are blocked"),
            "rate_limits": limits,
            "rate_limits_status": limits_status,
        }

    def start_turn(
        self,
        cwd: Path,
        prompt: str,
        on_event: EventCallback,
        thread_id: str | None = None,
        model: str | None = None,
        effort: str | None = None,
    ) -> dict[str, Any]:
        """Create/resume a context, then return the start acknowledgement.

        The caller owns cwd allocation and must never pass the service database
        or original project directory. Only this resolved directory is writable.
        No output is adopted by this transport; the engine must validate it.
        """
        cwd = Path(cwd).resolve(strict=True)
        if not cwd.is_dir() or not isinstance(prompt, str) or not prompt.strip():
            raise ValueError("A real attempt directory and a nonempty prompt are required")
        if not callable(on_event):
            raise TypeError("on_event must be callable")
        with self._start_lock:
            if not self._ready:
                preflight = self.preflight()
                if not preflight["ready"]:
                    code = "RUNTIME_UNAVAILABLE" if self._runtime["status"] == "BLOCKED" else "AUTH_REQUIRED"
                    raise ProviderError(code, preflight["reason"])
            self._ensure_started()
            with self._lock:
                if self._active:
                    raise ProviderError("BUSY", "A Codex turn is still running; wait or cancel it first")
                self._starting_callback = on_event
                if thread_id:
                    self._callbacks[thread_id] = on_event
            new_id = None
            try:
                params: dict[str, Any] = {
                    "cwd": str(cwd), "sandbox": "workspace-write", "approvalPolicy": "on-request",
                    "approvalsReviewer": "user",
                    "config": {"sandbox_workspace_write": {
                        "writable_roots": [], "network_access": False,
                        "exclude_slash_tmp": True, "exclude_tmpdir_env_var": True,
                    }},
                }
                if model:
                    params["model"] = model
                if thread_id:
                    params.update(threadId=thread_id, excludeTurns=True)
                result = self._rpc("thread/resume" if thread_id else "thread/start", params)
                new_id = result.get("thread", {}).get("id")
                if not isinstance(new_id, str) or (thread_id and new_id != thread_id):
                    raise ProviderError("INVALID_RESPONSE", "Codex did not return the requested thread")
                actual_model = result.get("model")
                if not isinstance(actual_model, str):
                    raise ProviderError("INVALID_RESPONSE", "Codex did not report its effective model")
                self._verify_thread_policy(result, cwd)
                # Resume can rejoin a running thread after reconnect. Never append
                # a duplicate turn when recovery finds an in-flight turn.
                active_turns = [t for t in result.get("thread", {}).get("turns", []) if t.get("status") == "inProgress"]
                if active_turns or result.get("thread", {}).get("status", {}).get("type") == "active":
                    raise ProviderError("RECOVERY_REQUIRED", "Existing thread has an active turn; reconnect to its events before starting another")
                chosen_effort = self._choose_effort(actual_model, effort)
                with self._lock:
                    self._callbacks[new_id] = on_event
                    # Registered before turn/start: completion can race its ack.
                    self._active[(new_id, "pending")] = time.monotonic()
                turn_params = {
                    "threadId": new_id, "cwd": str(cwd),
                    "input": [{"type": "text", "text": prompt}],
                    "model": actual_model,
                    "approvalPolicy": "on-request", "approvalsReviewer": "user",
                    "sandboxPolicy": {
                        "type": "workspaceWrite", "writableRoots": [str(cwd)],
                        "networkAccess": False, "excludeSlashTmp": True, "excludeTmpdirEnvVar": True,
                    },
                }
                if chosen_effort is not None:
                    turn_params["effort"] = chosen_effort
                ack = self._rpc("turn/start", turn_params)
                turn = ack.get("turn", {})
                turn_id = turn.get("id")
                if not isinstance(turn_id, str):
                    raise ProviderError("INVALID_RESPONSE", "Codex did not acknowledge a turn id")
                with self._lock:
                    started = self._active.pop((new_id, "pending"), None)
                    if started is not None and turn.get("status") not in {"completed", "failed", "interrupted"}:
                        self._active.setdefault((new_id, turn_id), started)
                return {"thread_id": new_id, "turn_id": turn_id, "model": actual_model, "effort": chosen_effort}
            except Exception:
                with self._lock:
                    if new_id:
                        self._active.pop((new_id, "pending"), None)
                raise
            finally:
                with self._lock:
                    self._starting_callback = None

    @staticmethod
    def _verify_thread_policy(result: dict[str, Any], cwd: Path) -> None:
        sandbox = result.get("sandbox", {})
        if (result.get("approvalPolicy") != "on-request" or result.get("approvalsReviewer") != "user"
                or sandbox.get("type") != "workspaceWrite" or sandbox.get("networkAccess", False)):
            raise ProviderError("POLICY_MISMATCH", "Codex did not apply the requested sandbox and user approval policy")
        if Path(result.get("cwd", "")).resolve() != cwd:
            raise ProviderError("POLICY_MISMATCH", "Codex returned a different working directory")
        for root in sandbox.get("writableRoots", []):
            if not Path(root).resolve().is_relative_to(cwd):
                raise ProviderError("POLICY_MISMATCH", "Codex inherited writable roots outside the attempt directory")

    def _choose_effort(self, model: str, requested: str | None) -> str | None:
        entry = next((m for m in self._models if m["model"] == model or m.get("id") == model), None)
        if not entry:
            raise ProviderError("MODEL_UNAVAILABLE", "The effective model is absent from the model catalog; select an available model")
        supported = [x.get("reasoningEffort") for x in entry.get("supportedReasoningEfforts", []) if isinstance(x, dict)]
        if requested is not None:
            if requested not in supported:
                raise ProviderError("EFFORT_UNAVAILABLE", "The selected model does not support that reasoning effort")
            return requested
        default = entry.get("defaultReasoningEffort")
        if isinstance(default, str) and default in supported:
            return default
        # model/list documents this as the suggested client default. When older
        # or inconsistent metadata cannot establish one, omit the per-turn
        # override and let the native server retain its own configuration.
        # None must never silently mean the most expensive supported effort.
        return None

    def respond(self, request_id: int | str, decision_payload: dict[str, Any]) -> None:
        """Answer one pending user request; never create persistent permission rules."""
        with self._lock:
            request = self._requests.get(request_id)
            if request is None:
                raise ProviderError("STALE_REQUEST", "This Codex request is no longer pending")
            self._validate_decision(request["method"], decision_payload)
            self._send({"id": request_id, "result": decision_payload})
            del self._requests[request_id]

    @staticmethod
    def _validate_decision(method: str, payload: dict[str, Any]) -> None:
        if not isinstance(payload, dict):
            raise ValueError("A structured user response is required")
        if method in {"item/commandExecution/requestApproval", "item/fileChange/requestApproval"}:
            if set(payload) != {"decision"} or payload["decision"] not in ("accept", "decline", "cancel"):
                raise ValueError("Only a one-time accept, decline, or cancel is supported")
        elif method == "item/tool/requestUserInput":
            answers = payload.get("answers")
            if set(payload) != {"answers"} or not isinstance(answers, dict) or not all(
                isinstance(key, str) and isinstance(value, dict) and set(value) == {"answers"}
                and isinstance(value["answers"], list) and all(isinstance(v, str) for v in value["answers"])
                for key, value in answers.items()
            ):
                raise ValueError("Expected answers keyed by question id with string answer lists")
        elif method == "item/permissions/requestApproval":
            # Generic permission-profile grants could add the service store as a
            # writable root. Keep them denied; ordinary one-time command requests
            # are separately reviewable. A future grant UI needs path validation.
            if payload != {"permissions": {}, "scope": "turn"}:
                raise ValueError("Permission-profile expansion is unsupported; decline with empty turn permissions")
        elif method == "mcpServer/elicitation/request":
            if payload.get("action") not in ("accept", "decline", "cancel") or not set(payload) <= {"action", "content"}:
                raise ValueError("Expected an MCP accept, decline, or cancel response")
        else:
            raise ValueError("Unsupported Codex user request")

    def cancel(self, thread_id: str, turn_id: str) -> dict[str, Any]:
        """Request interruption; success is the later turn/completed event."""
        self._ensure_started()
        with self._lock:
            if (thread_id, turn_id) not in self._active:
                raise ProviderError("STALE_TURN", "This Codex turn is not active on this connection")
        return self._rpc("turn/interrupt", {"threadId": thread_id, "turnId": turn_id})

    def _rpc(self, method: str, params: dict[str, Any]) -> dict[str, Any]:
        with self._lock:
            if self._failure:
                raise self._failure
            self._next_id += 1
            request_id = self._next_id
            waiter: dict[str, Any] = {"event": threading.Event(), "response": None}
            self._pending[request_id] = waiter
        try:
            self._send({"id": request_id, "method": method, "params": params})
            if not waiter["event"].wait(self.request_timeout):
                error = ProviderError("REQUEST_TIMEOUT", f"Codex {method} acknowledgement timed out; reconnect before retrying")
                self._fail(error)
                raise error
            response = waiter["response"]
            if isinstance(response, ProviderError):
                raise response
            if "error" in response:
                error = response["error"]
                code = error.get("code") if isinstance(error, dict) else "unknown"
                # Raw server messages may contain command text or login metadata.
                raise ProviderError("RPC_ERROR", f"Codex rejected {method} (code {code}); inspect the request and capabilities")
            result = response.get("result")
            if not isinstance(result, dict):
                raise ProviderError("INVALID_RESPONSE", f"Codex {method} returned a non-object result")
            return result
        finally:
            with self._lock:
                self._pending.pop(request_id, None)

    def _send(self, message: dict[str, Any]) -> None:
        encoded = (json.dumps(message, ensure_ascii=False, separators=(",", ":")) + "\n").encode("utf-8")
        if len(encoded) > self.max_frame_bytes:
            raise ProviderError("INPUT_LIMIT", "Codex request exceeds the message size limit; use workspace artifacts")
        with self._write_lock:
            if self._failure:
                raise self._failure
            if self._closed or not self._transport:
                raise ProviderError("CLOSED", "Codex connection is not available")
            try:
                self._transport.write_frame(encoded, timeout=self.request_timeout)
            except TransportError as exc:
                error = ProviderError(exc.code, str(exc))
                self._fail(error)
                raise error from exc
            except (BrokenPipeError, OSError, ValueError) as exc:
                error = ProviderError("PROCESS_EXIT", "Codex input stream closed; reconnect and inspect the interrupted run")
                self._fail(error)
                raise error from exc

    def _read_stdout(self) -> None:
        assert self._process and self._process.stdout
        try:
            while not self._stop.is_set():
                line = self._process.stdout.readline(self.max_frame_bytes + 1)
                if not line:
                    if not self._closed:
                        self._fail(ProviderError("PROCESS_EXIT", "Codex exited before the connection was closed"))
                    return
                self._stream_bytes += len(line)
                if len(line) > self.max_frame_bytes or self._stream_bytes > self.max_stream_bytes:
                    self._fail(ProviderError("OUTPUT_LIMIT", "Codex output exceeds the configured bound; inspect the interrupted run"))
                    return
                try:
                    message = json.loads(line.decode("utf-8"))
                except (ValueError, UnicodeDecodeError, RecursionError):
                    self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted invalid UTF-8 or JSON"))
                    return
                if not isinstance(message, dict):
                    self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted a non-object message"))
                    return
                self._receive(message)
        except (OSError, ValueError) as exc:
            if not self._closed:
                self._fail(ProviderError("PROCESS_EXIT", f"Codex output stream failed ({type(exc).__name__})"))

    def _receive(self, message: dict[str, Any]) -> None:
        if "method" not in message:
            if not isinstance(message.get("id"), (int, str)) or isinstance(message.get("id"), bool):
                self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted an invalid response id"))
                return
            with self._lock:
                waiter = self._pending.get(message.get("id"))
                if waiter is not None:
                    waiter["response"] = message
                    waiter["event"].set()
            return
        method = message["method"]
        params = message.get("params", {})
        if not isinstance(method, str) or not isinstance(params, dict):
            self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted an invalid notification"))
            return
        thread = params.get("thread")
        thread_id = params.get("threadId") or (thread.get("id") if isinstance(thread, dict) else None)
        if thread_id is not None and not isinstance(thread_id, str):
            self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted an invalid thread id"))
            return
        with self._lock:
            if method == "thread/started" and thread_id and thread_id not in self._callbacks and self._starting_callback:
                self._callbacks[thread_id] = self._starting_callback
            callback = self._callbacks.get(thread_id)
            if method == "turn/completed":
                turn = params.get("turn")
                if not isinstance(turn, dict) or not isinstance(turn.get("id"), str):
                    self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted an invalid completed turn"))
                    return
                self._active.pop((thread_id, turn["id"]), None)
                self._active.pop((thread_id, "pending"), None)
                for request_id, request in list(self._requests.items()):
                    if request["params"].get("threadId") == thread_id:
                        del self._requests[request_id]
            if "id" in message:
                if not isinstance(message["id"], (str, int)) or isinstance(message["id"], bool):
                    self._fail(ProviderError("PROTOCOL_ERROR", "Codex emitted an invalid request id"))
                    return
                if method not in _USER_REQUESTS or callback is None:
                    self._send({"id": message["id"], "error": {"code": -32601, "message": "Client does not implement this request"}})
                    return
                if message["id"] in self._requests:
                    self._fail(ProviderError("PROTOCOL_ERROR", "Codex reused an unresolved request id"))
                    return
                self._requests[message["id"]] = message
        # Account/auth notifications are deliberately not forwarded into a deck's
        # event log. Only events carrying the target thread identity are routed.
        if callback and thread_id:
            self._enqueue(callback, message)

    def _enqueue(self, callback: EventCallback, event: dict[str, Any]) -> None:
        try:
            self._events.put_nowait((callback, event))
        except queue.Full:
            self._fail(ProviderError("CONSUMER_BACKPRESSURE", "Codex event consumer fell behind; resume after processing queued events"))

    def _dispatch(self) -> None:
        while not self._stop.is_set() or not self._events.empty():
            try:
                callback, event = self._events.get(timeout=0.1)
            except queue.Empty:
                continue
            try:
                callback(event)
            except Exception as exc:
                # Callback failures are application integration failures. Stop
                # generation rather than silently dropping authoritative events.
                with self._lock:
                    self._failure_callbacks.append((event.get("params", {}).get("threadId"), callback))
                self._fail(ProviderError("CALLBACK_ERROR", f"Codex event consumer failed ({type(exc).__name__})"))
            finally:
                self._events.task_done()
        if self._failure:
            with self._lock:
                callbacks = list(self._failure_callbacks)
            unique = {id(callback): (thread_id, callback) for thread_id, callback in callbacks}
            for thread_id, callback in unique.values():
                try:
                    callback({"method": "provider/error", "params": {"code": self._failure.code, "message": str(self._failure), "threadId": thread_id}})
                except Exception:
                    # The original callback failure is retained in _failure.
                    pass

    def _read_stderr(self) -> None:
        assert self._process and self._process.stderr
        try:
            while not self._stop.is_set():
                chunk = self._process.stderr.read(4096)
                if not chunk:
                    return
                with self._lock:
                    self._stderr_tail.extend(chunk)
                    del self._stderr_tail[:-self.max_stderr_bytes]
        except (OSError, ValueError):
            return

    def _watchdog(self) -> None:
        last_tick = time.monotonic()
        while not self._stop.wait(0.1):
            now = time.monotonic()
            with self._lock:
                waiting = {request["params"].get("threadId") for request in self._requests.values()}
                for key, started in list(self._active.items()):
                    if key[0] in waiting:
                        self._active[key] += now - last_tick
                    elif now - started > self.turn_timeout:
                        self._fail(ProviderError("TURN_TIMEOUT", "Codex exceeded the active execution deadline; the run is interrupted"))
                        return
            last_tick = now

    def _fail(self, error: ProviderError) -> None:
        with self._lock:
            if self._failure or self._closed:
                return
            self._failure = error
            for thread_id, _turn_id in self._active:
                if thread_id in self._callbacks:
                    self._failure_callbacks.append((thread_id, self._callbacks[thread_id]))
            if self._starting_callback:
                self._failure_callbacks.append((None, self._starting_callback))
            self._stop.set()
            for waiter in self._pending.values():
                waiter["response"] = error
                waiter["event"].set()
        self._terminate()

    def _terminate(self) -> None:
        with self._termination_lock:
            if self._transport is None or self._terminated:
                return
            self._terminated = True
            self._transport.terminate()

    def close(self) -> None:
        """Stop the owned process group and release pipes within a bounded wait."""
        with self._lock:
            if self._closed:
                return
            self._closed = True
            self._stop.set()
            for waiter in self._pending.values():
                waiter["response"] = ProviderError("CLOSED", "Codex connection was closed")
                waiter["event"].set()
        self._terminate()
        for worker in self._threads:
            if worker is not threading.current_thread():
                worker.join(timeout=1)
        if self._transport:
            self._transport.close()
        with self._lock:
            self._requests.clear()
            self._active.clear()
            self._stderr_tail.clear()
